### PR TITLE
[Ready for Merge] Merge 1.9.12 from Upstream

### PR DESCRIPTION
**Pull request by fallengravity**
I will post a full changelog shortly. 

It should be noted Geth 1.9.10 introduced a bug on certain Windows and OSX machines. If the node is started in fast sync an interrupt signal will cause a segmentation violation. The workaround is to run in full sync (I didn't see this issue corrupting the DB but it might best not to mess with it).

Backtrace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4539a39]

goroutine 972 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).NumberU64(...)
	/Users/ethanvanballegooyen/Ether1/core/types/block.go:309
github.com/ethereum/go-ethereum/core.(*BlockChain).Rollback(0xc000090000, 0xc08c44e000, 0x800, 0x800)
	/Users/ethanvanballegooyen/Ether1/core/blockchain.go:921 +0x589
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processHeaders.func1(0xc003075d98, 0xc0004f9500)
	/Users/ethanvanballegooyen/Ether1/eth/downloader/downloader.go:1374 +0x1e5
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processHeaders(0xc0004f9500, 0x5582, 0x418b53, 0xc0081e0e20, 0x4fff120, 0xc000215600)
	/Users/ethanvanballegooyen/Ether1/eth/downloader/downloader.go:1393 +0x13b2
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func6(0x0, 0x0)
	/Users/ethanvanballegooyen/Ether1/eth/downloader/downloader.go:517 +0x48
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc0004f9500, 0xc0088b3a40, 0xc008ab5170)
	/Users/ethanvanballegooyen/Ether1/eth/downloader/downloader.go:534 +0x5b
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/Users/ethanvanballegooyen/Ether1/eth/downloader/downloader.go:534 +0xaf
```

Ethereum issue: https://github.com/ethereum/go-ethereum/issues/20585

### CODE REVIEW

**Comment by fallengravity** [comment]
Changelog:

# 1.9.9

Geth v1.9.9 is yet another hard fork release! Don't worry, it's not a hotfix for Istanbul. v1.9.9 ships and enables the next hard fork, Muir Glacier, scheduled for block #9200000, expected around the 6th of January, 2020 (and block #7117117 on Ropsten, expected more or less around the same time).

Apart from Muir Glacier, the release:

Simplifies and cleans up the internals of the miner package (#20335, #19396).
Fixes a regression in restoring a deleted chain from the freezer (#20403).
Fixes a data race in the new iterator based discovery code (#20421).
Fixes a pointer reference issue in ABI big.Int decoding (#20412).
Fixes the help message of certain geth subcommands (#20203).

# 1.9.10

Geth v1.9.10 is one of our usual maintenance releases. To make the first release of 2020 a bit more special though, we've also enabled the light client checkpoint oracle on mainnet (been running on all test nets for over 6 months now)!

Among the various tiny tweaks, more notable ones are:

Integrate DNS discovery, don't activate yet (#20437, #20524).
Bump the propagated transaction cap to 64KB (#20352, #20555).
Add propagated block integrity check before forwarding (#20546).
Continued removing deprecated types from the codebase (#20312).
Optimize memory allocations during trie traversal in hashing (#20529).
Handle an ABI ambiguity between Solidity and Vyper outputs (#20419).
Support WebSocket dialing from Go with custom HTTP configs (#20471).
Extend the ABI decoder to handle Solidity 6 view/pure modifiers (#20482).
Reorganize chain database writes to be less vulnerable to crashes (#20287).
Support exporting a block interval via RPC too, not just through the CLI (#20107).
And of course, fixes:

Fix issue where light servers disconnected each other (#20453).
Fix a goroutine leak in whisper v6 implementation. (#20520).
Fix discovery bootnode-fallback on blocked UDP (#20573).
Fix an RPC incompatibility for pending blocks (#20460).

# 1.9.11

Geth v1.9.11 was planned to be our next regular maintenance release, but enough niceties have piled up for it to become a feature release. This is also the reason why we delayed it by two weeks compared to our regular schedule.

The release ships three important new features:

DNS-based peer discovery is now enabled in Geth (#20592, #20660). From now on Geth nodes have two independent mechanisms to find peers. The DNS lists serve as a fallback mechanism when peers cannot be found through the DHT.

DNS-based discovery is a centralized mechanism, but we have tried to make the operation of this mechanism as transparent and permissionless as possible. The public lists used by default are generated by crawling the discovery DHT. At this time, there are ~1150 publicly routed Ethereum mainnet nodes in the default list. Our public lists also serve the Ropsten, Goerli and Rinkeby test networks. Nodes running any Ethereum client which implements EIP-868 and EIP-2124 will appear in the public lists automatically.

You can disable the use of DNS-based discovery using the --discovery.dns "" flag combination.

If you want to create a DNS-based node list for your private or public network, please check out our DNS Discovery Setup guide. We hope that organizations other than Ethereum Foundation will provide public lists in the future and will happily integrate those lists into the default one using the 'link' feature of EIP-1459.

Transaction announcements via eth/65 (EIP 2464) is now implemented and Geth<->Geth connections should use significantly less bandwidth (#20234) for exchanging transactions. Final numbers are anybody's guess though, as we need to wait for widespread network deployment. This feature depends on the eth/64 and eth/65 protocol updates, which are not yet supported in all Ethereum client implementations. While connections between compatible clients will use the new protocol, geth will remain compatible with eth/63 until the new protocol versions are sufficiently adopted by the public network.

The JavaScript engine underlying the Geth console and Clef rule engine was switched from Otto to Goja, which should bring it up to ECMAScript 5.1+ compliance. Not your latest and greatest .js environment of course, but significantly better and faster than before (#20470, #20599).

Minor features and fixes contained in the release:

Shave a few milliseconds off of each block via internal trie optimizations (#20481, #20488).
Optimize EVM BLOCKHASH opcode execution to handle the worst case better (#20589).
Check for RPC API namespace availability to detect typos in --rpcapi &co (#20597).
Add geth dumpgenesis to print the full genesis and chain config of a node (#20191).
Revert pending block number reporting during block retrieval (#20616).
Fix a JavaScript tracer panic when accessing illegal memory (#20612).
Fix an RPC connectivity issue around flaky connections (#20414).
Clean up C++ mainnet and Geth Görli bootnodes (#20610).
Fix bytes32 and bytes32[] support in Clef (#20609).

**Comment by fallengravity** [comment]
# 1.9.12

Geth v1.9.12 is a small bugfix release, mostly to keep a semi-regular schedule.

One small breaking change in the release is that eth_call will not default to your first account any more if you don't explicitly specify a sender. This was done to avoid the same input behaving differently in different environments. You should never do eth_call without explicitly setting a sender in the first place.

Changes:

Default to the zero (0x00...0) account for eth_call sender if none was specified (#20702).
Add missing CallOpts.SetFrom for mobile to permit setting a sender on calls (#20721).
Decouple constants in two EIPs applied together in Istanbul (#20646).
Fixes:

Fix a console regression that lost support for escape and unescape (#20700).
Fix failing CI runs due to randomness in tx fetcher scenario tests (#20712).
Fix a goroutine leak in transaction propagation (#20762).
Fix a possible data race in the downloader (#20690).
The release also includes a few changes towards supporting Go 1.14, but the switch-over is postponed until Go 1.14.1 is released due to an issue in Go around faulty Linux kernel detection.

For a full rundown of the changes please consult the Geth 1.9.12 release milestone.

**Comment by fallengravity** [comment]
1.9.12 appears to have fixed Geth 1.9.10's fast sync bug. I'm happy to call it safe to merge now.

**Comment by Dev-JamesR** [comment]
Merged Upstream Updates - 1.9.12

**Pull request merged**
